# fly.toml app configuration file generated for back-aged-log-7408 on 2024-06-25T17:01:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'back-aged-log-7408'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
    
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  APP_RUNTIME = '\App\FlySymfonyRuntime'